name: Documentation

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  test:
    name: "phpDocumentor"
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP 7.4
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
